{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "09f6eb59",
   "metadata": {
    "_execution_state": "idle",
    "_uuid": "051d70d956493feee0c6d64651c6a088724dca2a",
    "papermill": {
     "duration": 0.002882,
     "end_time": "2023-11-07T21:04:30.178449",
     "exception": false,
     "start_time": "2023-11-07T21:04:30.175567",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# Introduction\n",
    "\n",
    "Cyclistic Bike Share Case Study is part of the Google Data Analytics Course I have done. In this case I worked as a Junior Data Analyst in the marketing analyst team for a fictional company - Cyclistic, based in Chicago. I followed the steps of the data analysis process: ask, prepare, process, analyze, share, and act.\n",
    "\n",
    "\n",
    "# Scenario\n",
    "\n",
    "The director of marketing considers the company’s future success depends on maximizing the number of annual memberships. My team wants to understand how casual riders and annual members use Cyclistic bikes differently.\n",
    "\n",
    "\n",
    "# About the company\n",
    "\n",
    "Cyclistic is a bike-share program that features more than 5,800 bicycles and 600 docking stations. It offers reclining bikes, hand tricycles, and cargo bikes, making bike-share more inclusive to people with disabilities and riders who can’t use a standard two-wheeled bike. \n",
    "Cyclistic was launched in 2016 and throught the years has grown to a fleet of bicycles that are geotracked and locked into a network of 692 stations across Chicago. The bikes can be unlocked from one station and returned to any other station in the system anytime. \n",
    "\n",
    "Cyclistic’s marketing strategy relied on building general awareness and appealing to broad castomer segments by offering flexible pricing plans: single-ride passes, full-day passes, and annual memberships. \n",
    "Customers who purchase single-ride or full-day passes are referred to as casual riders. Customers who purchase annual memberships are Cyclistic members.\n",
    "\n",
    "\n",
    "# Ask\n",
    "\n",
    "### Business question:\n",
    "\n",
    "How do annual members and casual riders use Cyclistic bikes differently?\n",
    "\n",
    "### Business task\n",
    "\n",
    "Maximizing the number of annual memberships as key to future growth.\n",
    "\n",
    "### Stakeholders\n",
    "\n",
    "Key stakehoders:\n",
    "\n",
    "* Lily Moreno - the director of marketing who is responsible for the development of campaigns and initiatives to promote the bike-share program;\n",
    "* Cyclistic marketing analytics team - a team of data analysts who are responsible for collecting, analyzing, and reporting data that helps guide   Cyclistic marketing strategy;\n",
    "* Cyclistic executive team - the notoriously detail-oriented executive team will decide whether to approve the recommended marketing program.\n",
    "\n",
    "\n",
    "# Prepare\n",
    "\n",
    "### Data source\n",
    "\n",
    "I used Cyclistic’s historical trip data to analyze and identify trends. The data has been made available by Motivate International Inc. under this [license] (https://divvybikes.com/data-license-agreement).\n",
    "This is a public data but the data-privacy issues prohibit using riders’ personally identifiable information. This means that I won’t be able to connect pass purchases to credit card numbers to determine if casual riders live in the Cyclistic service area or if they have purchased multiple single passes.\n",
    "\n",
    "### Data organization\n",
    "\n",
    "I choosen the most recent year of Cyclistic trip data (from October 2022 to September 2023) and downloaded each files from [divvy-data] (https://divvy-tripdata.s3.amazonaws.com/index.html) as a zip Archive file. Then, data have been unzipped and saved as 12 CSV files, there is 1 file for each month. I created a folder on my desktop with 2 subfolders within - one for CSV files and another for XLS files. I used appropriate file-naming conventios for all of them. Next, I moved the downloaded files to the appropriate subfolder. Thanks to that, I have a copy of original data.\n",
    "\n",
    "This is structured data, organized in rows and columns. Each record represents one trip, and each trip has a unique field that identifies it: ride_id. \n",
    "\n",
    "### ROCCC\n",
    "\n",
    "I used ROCCC in terms of bias and credibility of data source.\n",
    "\n",
    "* Reliable and original\n",
    "This is public data that contains accurate, complete and unbiased info on Cyclistic’s historical bike trips.\n",
    "\n",
    "* Comprehensive and current\n",
    "This data source contain all the data needed to understand the different ways members and casual riders use Cyclistic bikes. The data is from the most relevant 12 months.\n",
    "\n",
    "* Cited\n",
    "This source is publicly available data provided by Cyclistic and the City of Chicago.\n",
    "\n",
    "\n",
    "# Process\n",
    "\n",
    "In order to answer the key business questions, I have conducted the data analysis process using Excel, R and Tableau tool.\n",
    "Initially, I wanted to use BigQuery tool to clean, manipulate and analyze the data, but because of memory limitation, I finally decided for cleaning, veryfication and transforming data in Microsoft Excel and R.\n",
    "\n",
    "### Data cleaning and manipulation\n",
    "\n",
    "#### Microsoft Excel - initial data cleaning and manipulation\n",
    "\n",
    "I got better familiarize with data by veryfying them in Excel worksheet as follow:\n",
    "\n",
    "1. Launched Microsoft Excel, opened each CSV file, saved it as an Excel Workbook file and put it in an appropriate subfolder I created before.\n",
    "2. Added two columns to all of the months:\n",
    "\n",
    "    + ride_length calculated the total ride length for each trip as subtracting the column \"started_at\" from the column \"ended_at\"; formatted as Time HH:MM:S;\n",
    "    + day_of_week calculated the day of the week for each ride started using the \"WEEKDAY\" command; formatted as General, noting that 1 = Monday and 7 = Sunday.\n",
    "    \n",
    "3. Conducted data verification and cleaning process:\n",
    "\n",
    "    * checking the data format,\n",
    "    * checking the primary key (ride_id) for duplicates values,\n",
    "    * removing rows where ride_id is longer than 16 characters,\n",
    "    * removing rows with missing values,\n",
    "    * deleting unnecessary columns from the data set (start_lat, start_lng, end_lat, end_lng),\n",
    "    * removing all rows where start_station_name or end_station_name is \"Base - 2132 W Hubbard\" (after checking the information, this station refers to a technical service station);\n",
    "    * removing all rows where start_station_id or end_station_id is \"Hubbard Bike-checking (LBS-WH-TEST)\";\n",
    "    * checking meaning start_station_name and end_station_name with * at the end of name (station with * in name refers to charging station);\n",
    "    * removing all rows where ride_length is less then or equal to 0;\n",
    "    * removing all rows from dataset where ride_length is less than 60 seconds (it probably caused  by mistake, especially start_station_name equal send_station_name);\n",
    "    * removing ride_id column after data verification and cleaning process.\n",
    "    \n",
    "  All steps were applied to each month separately.\n",
    "  \n",
    "4. Created pivot tables and charts for every month.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.0.5"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 3.937203,
   "end_time": "2023-11-07T21:04:30.303677",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2023-11-07T21:04:26.366474",
   "version": "2.4.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
